version: "3.9"

services:
  Demo-Project-Creation-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=localhost,Demo-Project-Creation-api
    command: gunicorn config.wsgi -b 0.0.0.0:8080
  Demo-Project-Creation-ui:
    build:
      context: apps/ui
    environment:
      - API_HOST=Demo-Project-Creation-api:8080
    ports:
      - "80:80"
    depends_on:
      - Demo-Project-Creation-api
    links:
      - Demo-Project-Creation-api
